Algoritmo "DepartamentoDeTrânsito"

Var
   ANO_ATUAL, DATA_NASC, IDADE: inteiro


Inicio
escreval ("Digite o ano atual ")
leia (ANO_ATUAL)
escreval ("Digite o ano de seu nascimento ")
leia (DATA_NASC)
IDADE <- ANO_ATUAL - DATA_NASC

escreval ("Você tem", IDADE, " anos.")

Se (IDADE >=18) entao
   escreval ("Parabéns, você atingiu a idade para começar a dirigir!")
Senao
     escreval ("Que pena, você ainda não atingiu a idade para dirigir.")
FimSe


      



Fimalgoritmo